image:
  file: .gitpod.Dockerfile

tasks:
  - name: Initialize & Configure AWS
    command: bash $GITPOD_REPO_ROOT/configure_aws_with_gitpod.sh
    openMode: tab-before
  - init: pip install -r requirements.txt
    openMode: tab-after
  - name: Shutdown daemon
    openMode: tab-after
    command: |
      function shutdown() {
        # Commands that will run on shutdown
        pip freeze > requirements.txt
        
      }

      trap 'shutdown; exit' SIGTERM;
      printf '\033[3J\033c\033[3J%s\n' 'Waiting for SIGTERM ...';
      exec {sfd}<> <(:);
      until read -t 3600 -u $sfd; do continue; done;
